export const bankNames = [
  'VietinBank',
  'Vietcombank',
  'BIDV',
  'Agribank',
  'OCB',
  'MBBank',
  'Techcombank',
  'ACB',
  'VPBank',
  'TPBank',
  'Sacombank',
  'HDBank',
  'VietCapitalBank',
  'SCB',
  'VIB',
  'SHB',
  'Eximbank',
  'MSB',
  'CAKE',
  'Ubank',
  'Timo',
  'ViettelMoney',
  'VNPTMoney',
  'SaigonBank',
  'BacABank',
  'PVcomBank',
  'MBV',
  'NCB',
  'ShinhanBank',
  'ABBANK',
  'VietABank',
  'NamABank',
  'PGBank',
  'VietBank',
  'BaoVietBank',
  'SeABank',
  'COOPBANK',
  'LPBank',
  'KienLongBank',
  'KBank',
  'KookminHN',
  'KEBHanaHCM',
  'KEBHANAHN',
  'MAFC',
  'Citibank',
  'KookminHCM',
  'VBSP',
  'Woori',
  'VRB',
  'UnitedOverseas',
  'StandardChartered',
  'PublicBank',
  'Nonghyup',
  'IndovinaBank',
  'IBKHCM',
  'IBKHN',
  'HSBC',
  'HongLeong',
  'GPBank',
  'Vikki',
  'DBSBank',
  'CIMB',
  'CBBank'
] as const

export type BankName = (typeof bankNames)[number]

export enum BankNameEnum {
  VietinBank = 'VietinBank',
  Vietcombank = 'Vietcombank',
  BIDV = 'BIDV',
  Agribank = 'Agribank',
  OCB = 'OCB',
  MBBank = 'MBBank',
  Techcombank = 'Techcombank',
  ACB = 'ACB',
  VPBank = 'VPBank',
  TPBank = 'TPBank',
  Sacombank = 'Sacombank',
  HDBank = 'HDBank',
  VietCapitalBank = 'VietCapitalBank',
  SCB = 'SCB',
  VIB = 'VIB',
  SHB = 'SHB',
  Eximbank = 'Eximbank',
  MSB = 'MSB',
  CAKE = 'CAKE',
  Ubank = 'Ubank',
  Timo = 'Timo',
  ViettelMoney = 'ViettelMoney',
  VNPTMoney = 'VNPTMoney',
  SaigonBank = 'SaigonBank',
  BacABank = 'BacABank',
  PVcomBank = 'PVcomBank',
  MBV = 'MBV',
  NCB = 'NCB',
  ShinhanBank = 'ShinhanBank',
  ABBANK = 'ABBANK',
  VietABank = 'VietABank',
  NamABank = 'NamABank',
  PGBank = 'PGBank',
  VietBank = 'VietBank',
  BaoVietBank = 'BaoVietBank',
  SeABank = 'SeABank',
  COOPBANK = 'COOPBANK',
  LPBank = 'LPBank',
  KienLongBank = 'KienLongBank',
  KBank = 'KBank',
  KookminHN = 'KookminHN',
  KEBHanaHCM = 'KEBHanaHCM',
  KEBHANAHN = 'KEBHANAHN',
  MAFC = 'MAFC',
  Citibank = 'Citibank',
  KookminHCM = 'KookminHCM',
  VBSP = 'VBSP',
  Woori = 'Woori',
  VRB = 'VRB',
  UnitedOverseas = 'UnitedOverseas',
  StandardChartered = 'StandardChartered',
  PublicBank = 'PublicBank',
  Nonghyup = 'Nonghyup',
  IndovinaBank = 'IndovinaBank',
  IBKHCM = 'IBKHCM',
  IBKHN = 'IBKHN',
  HSBC = 'HSBC',
  HongLeong = 'HongLeong',
  GPBank = 'GPBank',
  Vikki = 'Vikki',
  DBSBank = 'DBSBank',
  CIMB = 'CIMB',
  CBBank = 'CBBank'
}
