version: '3.8'

services:
  mysql:
    image: mysql:8.0.42
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: anhemiit123    # Mật khẩu root
      MYSQL_DATABASE: safes_software               # DB mặc định
      MYSQL_USER: root                   # User mặc định
      MYSQL_PASSWORD: anhemiit123           # Mật khẩu user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:

networks:
  backend:
    driver: bridge
