version: '3.8'

services:
  mysql:
    image: mysql:8.0.42
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: anhemiit123
      MYSQL_DATABASE: safes_software
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  adminer:
    container_name: hrm_adminer
    image: adminer
    ports:
      - "81:8080"
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
    driver: bridge
