version: '3.8'

services:
  mysql:
    image: mysql:8.0.42
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: anhemiit123
      MYSQL_DATABASE: safes_software
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: anhemiit123
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
    driver: bridge
